package dev.shaderbridge.model;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.google.gson.JsonPrimitive;
import com.google.gson.reflect.TypeToken;
import dev.shaderbridge.model.json.ModelParseException;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

/**
 * Parses JSON that serde itself produced from {@code sb_core::model} values (generated by
 * {@code java/src/test/rust/model-fixtures}), one test per serde representation: unit enums,
 * internally tagged, adjacently tagged with {@code "value"} and with {@code "name"}, transparent
 * newtypes, {@code skip_serializing_if}/{@code default} fields and maps with integer and enum keys.
 * Every parsed value is written back with {@link ModelJson} and must give the same JSON tree.
 */
class SerdeFixtureTest {
    private static JsonObject shapes;
    private static JsonElement packTree;
    private static CompiledPack pack;

    @BeforeAll
    static void load() throws Exception {
        shapes = JsonParser.parseString(ModelJsonTest.resource("serde_shapes.json")).getAsJsonObject();
        String json = ModelJsonTest.resource("compiled_pack_serde.json");
        packTree = JsonParser.parseString(json);
        pack = ModelJson.parse(json, CompiledPack.class);
    }

    /** Parses {@code shapes[key]} as a list and checks that each element serializes back to serde's JSON. */
    private static <T> List<T> shape(String key, TypeToken<List<T>> type) throws ModelParseException {
        JsonArray rust = shapes.getAsJsonArray(key);
        List<T> values = ModelJson.parse(rust.toString(), type);
        assertEquals(rust.size(), values.size(), key);
        for (int i = 0; i < values.size(); i++) {
            JsonElement java = JsonParser.parseString(ModelJson.toJson(values.get(i)));
            assertEquals(normalize(rust.get(i)), normalize(java), key + "[" + i + "] written back");
        }
        return values;
    }

    @Test
    void unitEnumsUseSerdeNames() throws ModelParseException {
        assertEquals(List.of(BlobKind.values()), shape("blob_kind", new TypeToken<List<BlobKind>>() { }));
        assertEquals(List.of(DepthMode.values()), shape("depth_mode", new TypeToken<List<DepthMode>>() { }));
        assertEquals(List.of(OutputTarget.values()), shape("output_target", new TypeToken<List<OutputTarget>>() { }));
        assertEquals(List.of(OptionKind.values()), shape("option_kind", new TypeToken<List<OptionKind>>() { }));
        assertEquals(List.of(DhStrategy.values()), shape("dh_strategy", new TypeToken<List<DhStrategy>>() { }));
        assertEquals(List.of(Severity.values()), shape("severity", new TypeToken<List<Severity>>() { }));
        assertEquals(List.of(ScalarKind.values()), shape("scalar_kind", new TypeToken<List<ScalarKind>>() { }));
        assertEquals(List.of(ShaderStage.values()), shape("shader_stage", new TypeToken<List<ShaderStage>>() { }));
        assertEquals(List.of(GeometryProgram.values()), shape("geometry_program", new TypeToken<List<GeometryProgram>>() { }));
        assertEquals(List.of(PassGroup.values()), shape("pass_group", new TypeToken<List<PassGroup>>() { }));
        assertEquals(List.of(AlphaFunc.values()), shape("alpha_func", new TypeToken<List<AlphaFunc>>() { }));
        assertEquals(List.of(BlendFactor.values()), shape("blend_factor", new TypeToken<List<BlendFactor>>() { }));
        assertEquals(List.of(TextureFormat.values()), shape("texture_format", new TypeToken<List<TextureFormat>>() { }));
    }

    @Test
    void resourceRefIsAdjacentlyTaggedWithValue() throws ModelParseException {
        List<ResourceRef> refs = shape("resource_ref", new TypeToken<List<ResourceRef>>() { });
        assertEquals(List.of(
            new ResourceRef.ColorTex(3),
            new ResourceRef.DepthTex(1),
            new ResourceRef.ShadowTex(0),
            new ResourceRef.ShadowTexHw(1),
            new ResourceRef.ShadowColor(2),
            new ResourceRef.Noise(),
            new ResourceRef.Atlas(),
            new ResourceRef.Lightmap(),
            new ResourceRef.Normals(),
            new ResourceRef.Specular(),
            new ResourceRef.Overlay(),
            new ResourceRef.DhDepthTex(0),
            new ResourceRef.DhBlockAtlas(),
            new ResourceRef.White(),
            new ResourceRef.CustomTexture("composite.cloudTex.3d"),
            new ResourceRef.Image("imgVoxel"),
            new ResourceRef.ColorImage(5),
            new ResourceRef.ShadowColorImage(1),
            new ResourceRef.Ssbo(4),
            new ResourceRef.UniformBlock("sb_Frame"),
            new ResourceRef.Unknown("mySampler")), refs);
        assertEquals(ResourceRef.class.getPermittedSubclasses().length, refs.size(), "every variant is covered");
    }

    @Test
    void screenEntryIsAdjacentlyTaggedWithValue() throws ModelParseException {
        assertEquals(List.of(
            new ScreenEntry.OptionEntry("SHADOWS"),
            new ScreenEntry.ScreenLink("LIGHTING"),
            new ScreenEntry.ProfileSelector(),
            new ScreenEntry.Empty(),
            new ScreenEntry.Rest()), shape("screen_entry", new TypeToken<List<ScreenEntry>>() { }));
    }

    @Test
    void uniformSourceIsAdjacentlyTaggedWithName() throws ModelParseException {
        assertEquals(List.of(
            new UniformSource.Builtin("frameTimeCounter"),
            new UniformSource.Custom("myCustom"),
            new UniformSource.Unset()), shape("uniform_source", new TypeToken<List<UniformSource>>() { }));
    }

    @Test
    void sizesAreInternallyTaggedWithAdjacentlyTaggedAxes() throws ModelParseException {
        assertEquals(List.of(
            new TargetSize.Relative(0.5f, 0.25f),
            new TargetSize.Absolute(64, 32),
            new TargetSize.PerAxis(new AxisSize.Relative(0.5f), new AxisSize.Absolute(64))), shape("target_size", new TypeToken<List<TargetSize>>() { }));
        assertEquals(List.of(new AxisSize.Relative(0.75f), new AxisSize.Absolute(128)), shape("axis_size", new TypeToken<List<AxisSize>>() { }));
        assertEquals(List.of(
            new ImageSize.Relative(0.5f, 1f),
            new ImageSize.Absolute1D(256),
            new ImageSize.Absolute2D(512, 256),
            new ImageSize.Absolute3D(64, 32, 16)), shape("image_size", new TypeToken<List<ImageSize>>() { }));
        assertEquals(List.of(new WorkGroups.Absolute(1, 2, 3), new WorkGroups.Relative(0.5f, 0.25f)), shape("work_groups", new TypeToken<List<WorkGroups>>() { }));
    }

    @Test
    void textureSourceAndResourceKindAreInternallyTagged() throws ModelParseException {
        assertEquals(List.of(
            new TextureSource.PackImage("textures/noise.png"),
            new TextureSource.Resource("minecraft:textures/atlas/blocks.png"),
            new TextureSource.Dynamic("minecraft:dynamic/lightmap_1"),
            new TextureSource.Raw("data/lut.dat", "2d_rect", 3, TextureFormat.RGBA16F, List.of(64, 32, 16), "RGBA", "HALF_FLOAT")),
            shape("texture_source", new TypeToken<List<TextureSource>>() { }));
        assertEquals(List.of(
            new ResourceKind.Sampler("2d", true, "float"),
            new ResourceKind.StorageImage("3d", "rgba16f", "uint", false, true),
            new ResourceKind.StorageImage("2d", null, "float", true, false),
            new ResourceKind.StorageBuffer(),
            new ResourceKind.UniformBuffer()), shape("resource_kind", new TypeToken<List<ResourceKind>>() { }));
    }

    @Test
    void programKindCarriesOptionalCharLetters() throws ModelParseException {
        assertEquals(List.of(
            new ProgramKind.Geometry(GeometryProgram.DAMAGED_BLOCK),
            new ProgramKind.Composite(PassGroup.COMPOSITE, 3),
            new ProgramKind.Compute(PassGroup.SHADOW_COMP, 2, 'b'),
            new ProgramKind.Compute(PassGroup.DEFERRED, 0, null),
            new ProgramKind.GeometryCompute(GeometryProgram.SHADOW, 'a'),
            new ProgramKind.GeometryCompute(GeometryProgram.SHADOW, null)), shape("program_kind", new TypeToken<List<ProgramKind>>() { }));
    }

    @Test
    void glslTypeSkipsAbsentArrays() throws ModelParseException {
        assertEquals(List.of(
            GlslType.FLOAT,
            GlslType.vector(ScalarKind.INT, 3),
            GlslType.matrix(3, 3),
            GlslType.matrix(3, 4),
            GlslType.vector(ScalarKind.BOOL, 2),
            GlslType.VEC4.withArray(5),
            GlslType.vector(ScalarKind.DOUBLE, 1)), shape("glsl_type", new TypeToken<List<GlslType>>() { }));
        assertEquals("mat3x4", GlslType.matrix(3, 4).glslName());
        assertEquals("{\"scalar\":\"float\",\"rows\":1,\"cols\":1}", ModelJson.toJson(GlslType.FLOAT), "None arrays are omitted like serde does");
    }

    @Test
    void deviceCapsDefaultsMatchSerde() throws ModelParseException {
        JsonArray rust = shapes.getAsJsonArray("device_caps");
        List<DeviceCaps> caps = ModelJson.parse(rust.toString(), new TypeToken<List<DeviceCaps>>() { });
        assertEquals(new DeviceCaps(true, true, true, true, false, 128, 8, true, null), caps.get(0));
        assertEquals(new DeviceCaps(true, true, true, true, false, 128, 8, false, 32), caps.get(1));
        assertEquals(new DeviceCaps(false, false, false, false, true, 256, 8, true, null), caps.get(2), "#[serde(default = \"default_true\")]");
        for (int i = 0; i < 2; i++) {
            assertEquals(normalize(rust.get(i)), normalize(JsonParser.parseString(ModelJson.toJson(caps.get(i)))));
        }
        assertTrue(!ModelJson.toJson(caps.get(0)).contains("max_descriptors_per_program"), "skip_serializing_if = Option::is_none");
    }

    @Test
    void nonFiniteFloatsThatSerdeWritesAsNullBecomeNaN() throws ModelParseException {
        JsonObject nan = shapes.getAsJsonObject("nan_floats");
        AlphaTest test = ModelJson.parse(nan.get("alpha_test").toString(), AlphaTest.class);
        assertEquals(AlphaFunc.GREATER, test.func());
        assertTrue(Float.isNaN(test.reference()));
        ViewportScale viewport = ModelJson.parse(nan.get("viewport").toString(), ViewportScale.class);
        assertTrue(Float.isNaN(viewport.scale()));
        assertEquals(0f, viewport.offsetX());
        assertEquals(nan.get("alpha_test"), JsonParser.parseString(ModelJson.toJson(test)), "written back as null, as serde does");
    }

    @Test
    void compiledPackMatchesSerde() throws IOException {
        assertEquals(CompiledPack.FORMAT_VERSION, pack.formatVersion());
        CompileEnvironment env = pack.info().environment();
        assertEquals(Arrays.asList(null, "2"), new ArrayList<>(env.extraMacros().values()));
        assertEquals(new DeviceCaps(true, true, true, true, false, 128, 8, false, 32), env.device());

        OptionsModel options = pack.options();
        assertEquals("", options.options().get(2).comment());
        assertNull(options.options().get(1).comment());
        assertEquals(1, options.screens().get("EMPTY").columns());
        assertEquals(List.of(), options.screens().get("EMPTY").entries());
        assertEquals(Map.of(), options.profiles().get("HIGH"));
        assertEquals(List.of("LOW"), List.copyOf(options.profileDisabledPrograms().keySet()));

        assertEquals(List.of(10001, -1), List.copyOf(pack.idMaps().blocks().keySet()));

        DimensionPipeline world0 = pack.dimension("world0").orElseThrow();
        assertEquals(List.of(GeometryProgram.TERRAIN, GeometryProgram.DAMAGED_BLOCK, GeometryProgram.DH_TERRAIN), List.copyOf(world0.geometry().keySet()));
        BlendMode translucent = new BlendMode(BlendFactor.SRC_ALPHA, BlendFactor.ONE_MINUS_SRC_ALPHA, BlendFactor.ONE, BlendFactor.ONE_MINUS_SRC_ALPHA);
        assertEquals(new GeometrySlot(0, GeometryProgram.TERRAIN, Map.of(), translucent, new AlphaTest(AlphaFunc.ALWAYS, 0)),
            world0.geometry().get(GeometryProgram.DAMAGED_BLOCK));
        assertEquals(new AlphaTest(AlphaFunc.GREATER, 0.1f), world0.geometry().get(GeometryProgram.TERRAIN).alphaTest());
        // A slot as older models wrote it: no blend, no alpha test.
        assertEquals(new GeometrySlot(1, GeometryProgram.DH_TERRAIN), world0.geometry().get(GeometryProgram.DH_TERRAIN));
        assertTrue(world0.programs().get(0).inheritBlend());
        // Slot variants keep serde's (insertion) order.
        Map<String, Integer> variants = world0.geometry().get(GeometryProgram.TERRAIN).variants();
        assertEquals(List.of("sodium_terrain", "vanilla_entity"), List.copyOf(variants.keySet()));
        assertEquals(List.of(3, 2), List.copyOf(variants.values()));
        assertEquals(5_000_000_000L, world0.targets().buffers().get(0).size());
        assertEquals(List.of(1f, 0.5f, 0.25f, 0f), world0.targets().colortex().get(1).clearColor());
        assertEquals(new TargetSize.PerAxis(new AxisSize.Relative(0.5f), new AxisSize.Absolute(64)), world0.targets().colortex().get(2).size());
        assertEquals(90f, world0.targets().shadow().fov());
        assertEquals(List.of(false, true, false, false, false, false, false, false), world0.targets().shadow().colorNearest());

        BlockMember weights = world0.uniforms().frame().member("weights").orElseThrow();
        assertEquals(GlslType.FLOAT.withArray(2), weights.ty());
        assertEquals(List.of(0.5f, 0.25f), weights.defaultValues());
        assertNull(world0.uniforms().frame().member("frameTimeCounter").orElseThrow().defaultValues());
        assertEquals(new SourceLocation("shaders.properties", 40, 3), world0.customUniforms().get(0).location());
        assertNull(world0.customUniforms().get(1).location());

        Program terrain = world0.programs().get(0);
        Map<Integer, BlendMode> perBuffer = new LinkedHashMap<>(terrain.blendPerBuffer());
        assertEquals(List.of(4, 0), List.copyOf(perBuffer.keySet()));
        assertNull(perBuffer.get(4));
        assertEquals(BlendFactor.SRC_ALPHA_SATURATE, perBuffer.get(0).srcAlpha());
        assertEquals(0.1f, terrain.alphaTest().reference());
        // An emulated comparison sampler: a plain sampler in the table, flagged on the use.
        assertFalse(terrain.bindingsUsed().get(0).shadowEmulated());
        assertTrue(terrain.bindingsUsed().get(1).shadowEmulated());
        assertEquals(new ResourceKind.Sampler("2d", false, "float"), world0.bindings().get("shadowtex1").orElseThrow().kind());
        assertEquals(Boolean.FALSE, terrain.cull());
        assertEquals(new BlobId(3), terrain.stage(ShaderStage.FRAGMENT).orElseThrow().glslVulkan());
        Program compute = world0.programs().get(2);
        assertNull(compute.drawProfile());
        assertNull(compute.stages().get(0).glslRenderpearl());
        assertEquals(new IndirectDispatch(4, 16), compute.compute().indirect());
        assertEquals(new ProgramKind.GeometryCompute(GeometryProgram.SHADOW, 'a'), world0.programs().get(3).kind());
        assertEquals(Integer.valueOf(4), world0.passes().get(2).program());

        assertEquals(new Diagnostic(Severity.ERROR, "spv.compile", "'foo' : undeclared identifier",
            new SourceLocation("lib/a.glsl", 7, 12), "world0/gbuffers_terrain", ShaderStage.TESS_EVAL), pack.diagnostics().get(0));
        assertEquals(new Diagnostic(Severity.INFO, "opt.screen-unknown-option", "note", null, null, null), pack.diagnostics().get(2));
        assertEquals(new BlobInfo(BlobKind.BYTES, 120, 3), pack.blobs().get(6));

        String written = ModelJson.toJson(pack);
        assertEquals(normalize(packTree), normalize(JsonParser.parseString(written)), "Java writes the JSON serde wrote");
        writeForRustCheck(written);
    }

    /**
     * Leaves the Java serialization next to the test working directory so that
     * {@code cargo run -- --check <file>} of the fixture generator can parse it back with serde.
     */
    private static void writeForRustCheck(String packJson) throws IOException {
        JsonObject out = new JsonObject();
        out.add("pack", JsonParser.parseString(packJson));
        out.add("environment", JsonParser.parseString(ModelJson.toJson(pack.info().environment())));
        Files.writeString(Path.of("model-fixture-roundtrip.json"), out.toString(), StandardCharsets.UTF_8);
    }

    /**
     * serde omits {@code skip_serializing_if} fields that Gson writes as {@code null}, and both
     * sides spell numbers differently ({@code 1} vs {@code 1.0}); neither changes the meaning.
     */
    static JsonElement normalize(JsonElement element) {
        if (element.isJsonObject()) {
            JsonObject out = new JsonObject();
            element.getAsJsonObject().entrySet().stream()
                .filter(e -> !e.getValue().isJsonNull())
                .sorted(Map.Entry.comparingByKey())
                .forEach(e -> out.add(e.getKey(), normalize(e.getValue())));
            return out;
        }
        if (element.isJsonArray()) {
            JsonArray out = new JsonArray();
            element.getAsJsonArray().forEach(e -> out.add(normalize(e)));
            return out;
        }
        if (element.isJsonPrimitive() && element.getAsJsonPrimitive().isNumber()) {
            return new JsonPrimitive(element.getAsBigDecimal().stripTrailingZeros());
        }
        return element;
    }
}
