//! Reference tables shared by the integration tests.

#![allow(dead_code)]

/// Section 3 ("UNIFORMS") of the research spec
/// (`research-OptiFine-Iris-shader-pack-format-specifi.md`), transcribed as
/// (name, GLSL type). `hideGUI` is listed with its Iris type (`bool`; OptiFine: `int`).
pub const SPEC_SECTION_3: &[(&str, &str)] = &[
    // Camera/player
    ("cameraPosition", "vec3"),
    ("previousCameraPosition", "vec3"),
    ("eyeAltitude", "float"),
    ("cameraPositionInt", "ivec3"),
    ("cameraPositionFract", "vec3"),
    ("previousCameraPositionInt", "ivec3"),
    ("previousCameraPositionFract", "vec3"),
    ("eyePosition", "vec3"),
    ("relativeEyePosition", "vec3"),
    ("playerLookVector", "vec3"),
    ("playerBodyVector", "vec3"),
    ("vehicleLookVector", "vec3"),
    ("relativeVehiclePosition", "vec3"),
    ("upPosition", "vec3"),
    ("eyeBrightness", "ivec2"),
    ("eyeBrightnessSmooth", "ivec2"),
    ("centerDepthSmooth", "float"),
    ("firstPersonCamera", "bool"),
    // Status
    ("isEyeInWater", "int"),
    ("isSpectator", "bool"),
    ("isRightHanded", "bool"),
    ("blindness", "float"),
    ("darknessFactor", "float"),
    ("darknessLightFactor", "float"),
    ("nightVision", "float"),
    ("playerMood", "float"),
    ("constantMood", "float"),
    ("currentPlayerHealth", "float"),
    ("maxPlayerHealth", "float"),
    ("currentPlayerHunger", "float"),
    ("maxPlayerHunger", "float"),
    ("currentPlayerArmor", "float"),
    ("maxPlayerArmor", "float"),
    ("currentPlayerAir", "float"),
    ("maxPlayerAir", "float"),
    ("isRiding", "bool"),
    ("vehicleInWater", "bool"),
    ("inSwimmingAnimation", "bool"),
    ("feetInWater", "bool"),
    ("isElytraFlying", "bool"),
    ("heavyFog", "bool"),
    ("is_sneaking", "bool"),
    ("is_sprinting", "bool"),
    ("is_hurt", "bool"),
    ("is_invisible", "bool"),
    ("is_burning", "bool"),
    ("is_on_ground", "bool"),
    ("hideGUI", "bool"),
    // System
    ("viewWidth", "float"),
    ("viewHeight", "float"),
    ("aspectRatio", "float"),
    ("screenBrightness", "float"),
    ("frameCounter", "int"),
    ("frameTime", "float"),
    ("frameTimeCounter", "float"),
    ("currentColorSpace", "int"),
    ("currentDate", "ivec3"),
    ("currentTime", "ivec3"),
    ("currentYearTime", "ivec2"),
    ("textureFilteringMode", "int"),
    ("anisotropicFiltering", "int"),
    // IDs
    ("heldItemId", "int"),
    ("heldItemId2", "int"),
    ("heldBlockLightValue", "int"),
    ("heldBlockLightValue2", "int"),
    ("heldBlockLightColor", "vec3"),
    ("heldBlockLightColor2", "vec3"),
    ("entityId", "int"),
    ("blockEntityId", "int"),
    ("currentRenderedItemId", "int"),
    ("vehicleId", "int"),
    ("currentSelectedBlockId", "int"),
    ("currentSelectedBlockPos", "vec3"),
    // World
    ("sunPosition", "vec3"),
    ("moonPosition", "vec3"),
    ("shadowLightPosition", "vec3"),
    ("sunAngle", "float"),
    ("shadowAngle", "float"),
    ("moonPhase", "int"),
    ("worldTime", "int"),
    ("worldDay", "int"),
    ("rainStrength", "float"),
    ("wetness", "float"),
    ("thunderStrength", "float"),
    ("lightningBoltPosition", "vec4"),
    ("endFlashPosition", "vec3"),
    ("endFlashIntensity", "float"),
    ("previousEndFlashIntensity", "float"),
    ("cloudTime", "float"),
    ("cloudHeight", "float"),
    ("ambientLight", "float"),
    ("bedrockLevel", "int"),
    ("heightLimit", "int"),
    ("logicalHeightLimit", "int"),
    ("seaLevel", "int"),
    ("hasCeiling", "bool"),
    ("hasSkylight", "bool"),
    // Biome
    ("biome", "int"),
    ("biome_category", "int"),
    ("biome_precipitation", "int"),
    ("rainfall", "float"),
    ("temperature", "float"),
    // Rendering
    ("near", "float"),
    ("far", "float"),
    ("fogColor", "vec3"),
    ("skyColor", "vec3"),
    ("fogMode", "int"),
    ("fogShape", "int"),
    ("fogDensity", "float"),
    ("fogStart", "float"),
    ("fogEnd", "float"),
    ("alphaTestRef", "float"),
    ("entityColor", "vec4"),
    ("blendFunc", "ivec4"),
    ("atlasSize", "ivec2"),
    ("gtextureSize", "ivec2"),
    ("gtextureId", "int"),
    ("textureReloadCount", "int"),
    ("renderStage", "int"),
    ("chunkFadeTimeInv", "float"),
    ("pi", "float"),
    // Matrices
    ("gbufferModelView", "mat4"),
    ("gbufferModelViewInverse", "mat4"),
    ("gbufferPreviousModelView", "mat4"),
    ("gbufferProjection", "mat4"),
    ("gbufferProjectionInverse", "mat4"),
    ("gbufferPreviousProjection", "mat4"),
    ("shadowModelView", "mat4"),
    ("shadowModelViewInverse", "mat4"),
    ("shadowProjection", "mat4"),
    ("shadowProjectionInverse", "mat4"),
    ("dhProjection", "mat4"),
    ("dhProjectionInverse", "mat4"),
    ("dhPreviousProjection", "mat4"),
    // DH scalars
    ("dhNearPlane", "float"),
    ("dhFarPlane", "float"),
    ("dhRenderDistance", "int"),
    // Core-profile names
    ("modelViewMatrix", "mat4"),
    ("modelViewMatrixInverse", "mat4"),
    ("projectionMatrix", "mat4"),
    ("projectionMatrixInverse", "mat4"),
    ("normalMatrix", "mat3"),
    ("textureMatrix", "mat4"),
    ("colorModulator", "vec4"),
    ("chunkOffset", "vec3"),
    ("modelOffset", "vec3"),
    // OptiFine-only (types from OptiFine shaders.txt)
    ("instanceId", "int"),
    ("bossBattle", "int"),
    ("spriteBounds", "vec4"),
    ("terrainTextureSize", "ivec2"),
    ("terrainIconSize", "int"),
];

/// OptiFine boolean custom-uniform parameters (OptiFine `shaders.properties`).
pub const OPTIFINE_BOOL_PARAMETERS: &[&str] = &[
    "is_alive",
    "is_burning",
    "is_child",
    "is_glowing",
    "is_hurt",
    "is_in_lava",
    "is_in_water",
    "is_invisible",
    "is_on_ground",
    "is_ridden",
    "is_riding",
    "is_sneaking",
    "is_sprinting",
    "is_wet",
];

/// The uniform table of OptiFine `shaders.txt` ("Uniforms" section), with OptiFine's
/// declared types.
pub const OPTIFINE_DOC: &[(&str, &str)] = &[
    ("heldItemId", "int"),
    ("heldBlockLightValue", "int"),
    ("heldItemId2", "int"),
    ("heldBlockLightValue2", "int"),
    ("fogMode", "int"),
    ("fogStart", "float"),
    ("fogEnd", "float"),
    ("fogShape", "int"),
    ("fogDensity", "float"),
    ("fogColor", "vec3"),
    ("skyColor", "vec3"),
    ("worldTime", "int"),
    ("worldDay", "int"),
    ("moonPhase", "int"),
    ("frameCounter", "int"),
    ("frameTime", "float"),
    ("frameTimeCounter", "float"),
    ("sunAngle", "float"),
    ("shadowAngle", "float"),
    ("rainStrength", "float"),
    ("aspectRatio", "float"),
    ("viewWidth", "float"),
    ("viewHeight", "float"),
    ("near", "float"),
    ("far", "float"),
    ("sunPosition", "vec3"),
    ("moonPosition", "vec3"),
    ("shadowLightPosition", "vec3"),
    ("upPosition", "vec3"),
    ("cameraPosition", "vec3"),
    ("previousCameraPosition", "vec3"),
    ("gbufferModelView", "mat4"),
    ("gbufferModelViewInverse", "mat4"),
    ("gbufferPreviousModelView", "mat4"),
    ("gbufferProjection", "mat4"),
    ("gbufferProjectionInverse", "mat4"),
    ("gbufferPreviousProjection", "mat4"),
    ("shadowProjection", "mat4"),
    ("shadowProjectionInverse", "mat4"),
    ("shadowModelView", "mat4"),
    ("shadowModelViewInverse", "mat4"),
    ("wetness", "float"),
    ("eyeAltitude", "float"),
    ("eyeBrightness", "ivec2"),
    ("eyeBrightnessSmooth", "ivec2"),
    ("terrainTextureSize", "ivec2"),
    ("terrainIconSize", "int"),
    ("isEyeInWater", "int"),
    ("nightVision", "float"),
    ("blindness", "float"),
    ("screenBrightness", "float"),
    ("hideGUI", "int"),
    ("centerDepthSmooth", "float"),
    ("atlasSize", "ivec2"),
    ("spriteBounds", "vec4"),
    ("entityColor", "vec4"),
    ("entityId", "int"),
    ("blockEntityId", "int"),
    ("blendFunc", "ivec4"),
    ("instanceId", "int"),
    ("playerMood", "float"),
    ("renderStage", "int"),
    ("bossBattle", "int"),
    ("modelViewMatrix", "mat4"),
    ("modelViewMatrixInverse", "mat4"),
    ("projectionMatrix", "mat4"),
    ("projectionMatrixInverse", "mat4"),
    ("textureMatrix", "mat4"),
    ("normalMatrix", "mat3"),
    ("colorModulator", "vec4"),
    ("modelOffset", "vec3"),
    ("alphaTestRef", "float"),
    ("darknessFactor", "float"),
    ("darknessLightFactor", "float"),
];
