//! Shared types for ShaderBridge.
//!
//! Everything in [`model`] is part of the cross-component contract described in
//! `docs/ARCHITECTURE.md` (CompiledPack JSON consumed by the Java mod and by
//! `sb-runtime`). Change it only together with every consumer.

pub mod diag;
pub mod format;
pub mod glsl_type;
pub mod model;
pub mod program;
pub mod source;
pub mod stage;

pub use diag::{Diagnostic, Diagnostics, Severity, SourceLocation};
pub use format::TextureFormat;
pub use glsl_type::{GlslType, ScalarKind};
pub use program::{GeometryProgram, PassGroup, ProgramName};
pub use source::{normalize_pack_path, MemorySources, SourceProvider};
pub use stage::ShaderStage;

/// Version of the CompiledPack JSON format. Bump on incompatible changes.
pub const MODEL_FORMAT_VERSION: u32 = 1;

/// ShaderBridge version string (crate version).
pub const SHADERBRIDGE_VERSION: &str = env!("CARGO_PKG_VERSION");

/// Prefix reserved for identifiers generated by ShaderBridge in translated GLSL.
pub const RESERVED_PREFIX: &str = "sb_";
